plugins {
    id "com.android.application"
}

android {
    namespace "com.studiorad.tarefaswhatsapp"
    compileSdk 35

    defaultConfig {
        applicationId "com.studiorad.tarefaswhatsapp"
        minSdk 23
        targetSdk 35
        versionCode 7
        versionName "2.6.0"
    }
}

dependencies {
    implementation "androidx.core:core:1.13.1"
}
