name: Gerar APK Android

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - tarefas-whatsapp-apk
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Gerar APK Debug
        run: gradle :app:assembleDebug --no-daemon

      - name: Publicar APK
        uses: actions/upload-artifact@v4
        with:
          name: Tarefas-WhatsApp-APK
          path: app/build/outputs/apk/debug/app-debug.apk
